In [57]:
import numpy as np

In [4]:
x = np.array([[1, 2], [3, 4]])
x + 2

array([[3, 4],
       [5, 6]])

In [14]:
y = np.linspace(5,6, 3)
y

array([5. , 5.5, 6. ])

In [55]:
A = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

A[2:, :2 ]

array([[70, 80]])

In [56]:
import numpy as np

marks = np.array([45, 80, 67, 90, 30, 55])

print(marks > 60)

print(marks[marks > 60])

[False  True  True  True False False]
[80 67 90]


In [58]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([10,20])

print(A + B)

[[11 22]
 [13 24]]


In [68]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a =a.reshape(-1,4)
print(a.T)
a.flatten()

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
A = np.array([[2,3],
              [4,5]])

B = np.array([[4,5],
              [6,7]])

c = np.dot(A,B)
d = A@B
e = A*B

print(c)
print(d)
print(e)

[[26 31]
 [46 55]]
[[26 31]
 [46 55]]
[[ 8 15]
 [24 35]]


In [79]:
A = np.array([
    [4,7],
    [2,6]
])

b = np.linalg.det(A)
print(f"Determinant of A is: {b:.2f}")

Determinant of A is: 10.00
